### ISSUE TITLE
How to use _2?

### ISSUE THREAD

**Issue by joneshf** [Gabriel439/Haskell-Total-Library#2]
The example shows that you can use `_1` https://github.com/Gabriel439/Haskell-Total-Library/blob/master/src/Lens/Family/Total.hs#L73-L77
But trying something similar with `_2` doesn't seem to work.

``` haskell
module Tuple where

import Lens.Family.Total
import Lens.Family.Stock

foo :: (Int, Bool) -> String
foo = _case
    & on _2 show
```

The error is:

```
➜  totally  cabal build
Building totally-0.1.0.0...
Preprocessing library totally-0.1.0.0...
[1 of 1] Compiling Tuple            ( src/Tuple.hs, dist/build/Tuple.o )

src/Tuple.hs:7:7:
    No instance for (Empty Int) arising from a use of ‘_case’
    In the first argument of ‘(&)’, namely ‘_case’
    In the expression: _case & on _2 show
    In an equation for ‘foo’: foo = _case & on _2 show
```

It seems like it might be because the tuple instance is only defined for `instance Empty a => Empty ((,) a b) ...`

ghc takes it as a duplicate instance if I attempt to define this instance in addition:

``` haskell
instance Empty b => Empty ((,) a b) where
    impossible (_, b) = impossible b
```

```
➜  Haskell-Total-Library git:(master) ✗ cabal build
Building total-1.0.1...
Preprocessing library total-1.0.1...
[1 of 1] Compiling Lens.Family.Total ( src/Lens/Family/Total.hs, dist/build/Lens/Family/Total.o )

src/Lens/Family/Total.hs:124:10:
    Duplicate instance declarations:
      instance Empty a => Empty (a, b)
        -- Defined at src/Lens/Family/Total.hs:124:10
      instance Empty b => Empty (a, b)
        -- Defined at src/Lens/Family/Total.hs:127:10
```

And attempting to have both parts be constraints forces you to match all cases in the function (which isn't as intended.)

Any ideas what can be done about this? Is it something simple I'm missing?

**Comment by Gabriella439** [comment]
Yeah, that's why I only provide one instance for the left field of the tuple because if you provide the instance for the right field, too, then you get overlapping instances.

However, you can work around this by just directly inserting what you would have written for your type class instance in place of `_case` instead of relying on Haskell's type class resolution system.  In this case, that means replacing `_case` with  `_case . snd`:

``` haskell
_case . snd
    & on _2 show
```

... and that will work.  It's a hacky workaround, but that's the only general solution I know of.

**Comment by joneshf** [comment]
Hmm, that's a bit more convoluted. I think I'll stick to using this for Prisms. Thanks!
